/**
 * /blog/[slug] — single AI-generated blog post.
 *
 * Renders Markdown safely. Uses Admin SDK on the server (same rationale
 * as novel pages: gRPC client SDK breaks in Vercel serverless).
 */
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { adminDb } from '@/lib/firebaseAdmin';
import { serializeFirestore } from '@/lib/serialize';
import { absoluteUrl, SITE_NAME, SITE_LOGO_PATH } from '@/lib/site';
import TopNavBarClientWrapper from '@/components/TopNavBarClientWrapper';
import { Calendar, Clock, Tag } from 'lucide-react';

export const dynamic = 'force-dynamic';
export const revalidate = 300;

interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  contentMarkdown: string;
  coverUrl?: string;
  tags?: string[];
  estimatedReadMinutes?: number;
  kind?: 'review' | 'listicle';
  relatedNovelSlug?: string;
  createdAt?: number;
}

async function fetchPost(slug: string): Promise<BlogPost | null> {
  const snap = await adminDb().collection('blog_posts').doc(slug).get();
  if (!snap.exists) return null;
  return serializeFirestore({ slug: snap.id, ...snap.data() }) as BlogPost;
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = await fetchPost(slug);
  if (!post) return { title: 'Bài viết không tồn tại' };
  const canonical = absoluteUrl(`/blog/${slug}`);
  return {
    title: post.title,
    description: post.excerpt,
    alternates: { canonical },
    openGraph: {
      title: post.title,
      description: post.excerpt,
      url: canonical,
      siteName: SITE_NAME,
      images: post.coverUrl ? [{ url: post.coverUrl, width: 1200, height: 630 }] : undefined,
      locale: 'vi_VN',
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.excerpt,
      images: post.coverUrl ? [post.coverUrl] : undefined,
    },
  };
}

/**
 * Minimal but safe Markdown → HTML renderer.
 * We don't pull a full markdown library because: (a) ship size,
 * (b) our content is generated by Gemini with a constrained format we
 * fully control. We support: H2/H3, paragraphs, **bold**, links.
 */
function markdownToHtml(md: string): string {
  // Escape any raw HTML the model might emit before we add our own.
  const esc = md
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  const lines = esc.split(/\r?\n/);
  const out: string[] = [];
  let para: string[] = [];
  const flushPara = () => {
    if (para.length === 0) return;
    let text = para.join(' ');
    text = text.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    text = text.replace(/\[([^\]]+)\]\((\/[^)]+)\)/g,
      '<a class="text-primary hover:underline" href="$2">$1</a>');
    text = text.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,
      '<a class="text-primary hover:underline" target="_blank" rel="noopener" href="$2">$1</a>');
    out.push(`<p class="mb-5 leading-relaxed text-text-main/90">${text}</p>`);
    para = [];
  };

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) { flushPara(); continue; }
    if (trimmed.startsWith('### ')) {
      flushPara();
      out.push(`<h3 class="text-xl font-black mt-8 mb-3 text-text-main">${trimmed.slice(4)}</h3>`);
      continue;
    }
    if (trimmed.startsWith('## ')) {
      flushPara();
      out.push(`<h2 class="text-2xl md:text-3xl font-black mt-10 mb-4 text-text-main">${trimmed.slice(3)}</h2>`);
      continue;
    }
    if (trimmed.startsWith('# ')) {
      flushPara();
      out.push(`<h1 class="text-3xl font-black mt-10 mb-4 text-text-main">${trimmed.slice(2)}</h1>`);
      continue;
    }
    para.push(trimmed);
  }
  flushPara();
  return out.join('\n');
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = await fetchPost(slug);
  if (!post) notFound();

  const dateStr = post.createdAt ? new Date(post.createdAt).toLocaleDateString('vi-VN', { year: 'numeric', month: 'long', day: 'numeric' }) : '';

  // BlogPosting JSON-LD for Google rich result.
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.excerpt,
    image: post.coverUrl ? [post.coverUrl] : undefined,
    datePublished: post.createdAt ? new Date(post.createdAt).toISOString() : undefined,
    dateModified: post.createdAt ? new Date(post.createdAt).toISOString() : undefined,
    author: { '@type': 'Organization', name: SITE_NAME, url: absoluteUrl('/') },
    publisher: {
      '@type': 'Organization',
      name: SITE_NAME,
      logo: { '@type': 'ImageObject', url: absoluteUrl(SITE_LOGO_PATH) },
    },
    mainEntityOfPage: { '@type': 'WebPage', '@id': absoluteUrl(`/blog/${post.slug}`) },
    keywords: post.tags?.join(', '),
  };

  return (
    <>
      <TopNavBarClientWrapper />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }}
      />
      <article className="w-full bg-background text-text-main min-h-screen">
        {post.coverUrl && (
          <div className="w-full aspect-[3/1] md:aspect-[5/2] overflow-hidden relative">
            <img src={post.coverUrl} alt={post.title} className="w-full h-full object-cover" />
            <div className="absolute inset-0 bg-gradient-to-t from-background to-transparent" />
          </div>
        )}
        <header className="max-w-3xl mx-auto px-4 pt-12 pb-6">
          <Link href="/blog" className="text-sm text-muted hover:text-primary transition-colors">
            ← Quay lại Blog
          </Link>
          <h1 className="text-3xl md:text-5xl font-black tracking-tight mt-4 mb-4">{post.title}</h1>
          <p className="text-muted text-lg mb-6">{post.excerpt}</p>
          <div className="flex items-center gap-4 text-xs text-muted flex-wrap">
            {dateStr && <span className="flex items-center gap-1"><Calendar className="size-3" /> {dateStr}</span>}
            {post.estimatedReadMinutes && (
              <span className="flex items-center gap-1"><Clock className="size-3" /> {post.estimatedReadMinutes} phút đọc</span>
            )}
            <span className="flex items-center gap-1 text-yellow-500">
              <Tag className="size-3" /> AI-assisted
            </span>
          </div>
        </header>

        <div
          className="max-w-3xl mx-auto px-4 pb-12 prose-content"
          dangerouslySetInnerHTML={{ __html: markdownToHtml(post.contentMarkdown) }}
        />

        {post.tags && post.tags.length > 0 && (
          <div className="max-w-3xl mx-auto px-4 pb-12 flex flex-wrap gap-2">
            {post.tags.map((t) => (
              <span key={t} className="text-xs px-3 py-1 rounded-full bg-surface border border-accent/10 text-muted">
                #{t}
              </span>
            ))}
          </div>
        )}

        {post.relatedNovelSlug && (
          <div className="max-w-3xl mx-auto px-4 pb-24">
            <Link
              href={`/truyen/${post.relatedNovelSlug}`}
              className="block p-6 rounded-2xl bg-primary/10 border border-primary/30 hover:bg-primary/20 transition"
            >
              <div className="text-xs uppercase tracking-widest text-primary font-black mb-1">Truyện được nhắc tới</div>
              <div className="font-black text-lg">→ Đọc miễn phí 2 chương đầu tại đây</div>
            </Link>
          </div>
        )}
      </article>
    </>
  );
}
